
import { MenuItem, AddOn, Language } from './types';

export const THEME_INFO = {
  title: "Nyonya Heritage Tour",
  titleZh: "娘惹文化之旅",
  dateRange: "Jan 19 - Jan 23",
  cutoffTime: "8:00 PM",
  cutoffTimeZh: "晚上 8:00",
  isHalal: false,
  bankName: "Hong Leong Bank",
  bankAccount: "38900171282",
  accountName: "Sam Ai Sia",
  tngPhoneNumber: "+6017-9653871",
  ownerEmail: "thewanderingspoon@outlook.com",
  discountRate: 0.0,
  heroImage: ""
};

export const DEFAULT_HERO_IMAGE = "";

export const PLACEHOLDER_IMAGE = "";

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'mon_ayam_pongteh',
    day: 'Monday',
    dayZh: '星期一',
    dayIndex: 1,
    title: 'Ayam Pongteh',
    titleZh: '娘惹豆酱鸡',
    description: 'Slow-braised chicken with fermented soy bean paste and potatoes.',
    descriptionZh: '慢火焖制的豆酱马铃薯鸡肉。',
    price: 15.00,
    image: '',
    maxInventory: 20,
    allergies: ['Soy', 'Gluten'],
    allergiesZh: ['大豆', '麸质'],
    sideDishes: 'Fragrant Blue Pea Flower Rice, Nyonya Achar (Pickled Vegetables), Sambal Belacan',
    sideDishesZh: '蓝花饭，娘惹阿查（腌菜），参巴辣椒',
    story: 'This dish traces back to the 16th century Chinese immigrants in Malacca...',
    storyZh: '这道菜追溯到16世纪马六甲的中国移民...'
  },
  {
    id: 'tue_udang_masak_lemak',
    day: 'Tuesday',
    dayZh: '星期二',
    dayIndex: 2,
    title: 'Udang Masak Lemak Nenas',
    titleZh: '黄梨椰浆虾',
    description: 'Prawns cooked in a rich coconut curry with tangy pineapple.',
    descriptionZh: '香浓椰浆咖喱配上酸甜黄梨和鲜虾。',
    price: 18.00,
    image: '',
    maxInventory: 15,
    allergies: ['Shellfish', 'Crustaceans'],
    allergiesZh: ['贝类', '甲壳类'],
    sideDishes: 'Steamed Jasmine Rice, Stir-fried Kangkung Belacan, Fried Egg',
    sideDishesZh: '茉莉香米饭，马来风光，荷包蛋',
    story: 'This creamy coconut base combined with tangy pineapple represents the perfect balance of Peranakan flavors.',
    storyZh: '这款浓郁的椰奶基底与酸甜黄梨相结合，完美的展现了土生华人的风味平衡。'
  },
  {
    id: 'wed_laksa',
    day: 'Wednesday',
    dayZh: '星期三',
    dayIndex: 3,
    title: 'Nyonya Laksa',
    titleZh: '娘惹叻沙',
    description: 'Rice noodles in a rich and spicy coconut soup base.',
    descriptionZh: '香浓辛辣椰浆汤底配米粉。',
    price: 15.00,
    image: '',
    maxInventory: 25,
    allergies: ['Shellfish', 'Coconut', 'Egg'],
    allergiesZh: ['贝类', '椰子', '鸡蛋'],
    sideDishes: 'Otak-otak (Grilled Fish Cake), Cucumber Slices, Hard Boiled Egg',
    sideDishesZh: '乌达（烤鱼饼），黄瓜片，水煮蛋',
    story: 'Likely the most famous Nyonya dish, our Laksa uses a unique blend of 15 different spices and aromatics.',
    storyZh: '这可能是最著名的娘惹菜肴，我们的叻沙融合了15种不同的香料和香气。'
  },
  {
    id: 'thu_kari_kapitan',
    day: 'Thursday',
    dayZh: '星期四',
    dayIndex: 4,
    title: 'Curry Kapitan',
    titleZh: '甲必丹咖喱鸡',
    description: 'A drier, thicker version of chicken curry with kaffir lime leaves.',
    descriptionZh: '浓郁干咖喱鸡配疯柑叶。',
    price: 16.00,
    image: '',
    maxInventory: 0, // Simulating Sold Out
    allergies: ['Nuts', 'Shrimp Paste'],
    allergiesZh: ['坚果', '虾酱'],
    sideDishes: 'Turmeric Glutinous Rice, Kari Sayur (Vegetable Curry), Pappadom',
    sideDishesZh: '黄姜糯米饭，蔬菜咖喱，印度脆饼',
    story: 'The "Captain\'s Curry" was created for British masters by their Nyonya cooks, blending local spices with Western tastes.',
    storyZh: '“船长咖喱”是由娘惹厨师为英国主人创作的，将当地香料与西方口味融为一体。'
  },
  {
    id: 'fri_ikan_gerang_asam',
    day: 'Friday',
    dayZh: '星期五',
    dayIndex: 5,
    title: 'Ikan Gerang Asam',
    titleZh: '亚参酸辣鱼',
    description: 'Spicy and sour fish stew with tamarind and okra.',
    descriptionZh: '酸辣亚参鱼配羊角豆。',
    price: 18.00,
    image: '',
    maxInventory: 10,
    allergies: ['Fish', 'Shrimp Paste'],
    allergiesZh: ['鱼类', '虾酱'],
    sideDishes: 'Steamed White Rice, Sambal Petai with Prawns, Tempeh Chips',
    sideDishesZh: '白米饭，参巴臭豆虾，天贝脆片',
    story: 'A sour and spicy fish stew that uses tamarind and fresh herbs to create a refreshing yet deeply flavorful profile.',
    storyZh: '一款酸辣鱼炖，使用罗望子和新鲜草药创造出清新而浓郁的风味。'
  }
];

export const ADD_ONS: AddOn[] = [
  {
    id: 'fruit',
    title: 'Seasonal Fruit Cup',
    titleZh: '时令水果杯',
    price: 4.00,
    type: 'fruit'
  },
  {
    id: 'drink',
    title: 'The Daily Infusion',
    titleZh: '每日特饮',
    price: 5.00,
    type: 'drink'
  }
];



export const TEXTS = {
  [Language.EN]: {
    addToCart: "Add to Order",
    soldOut: "Sold Out",
    limitReached: "Max Limit",
    menuHeader: "Weekly Menu",
    addOnsHeader: "Enhance Your Experience",
    cartTotal: "Total",
    next: "Next",
    back: "Back",
    detailsHeader: "Delivery Details",
    detailsSubheader: "Please provide your contact and delivery information so we can get your delicious meal to you.",
    contactInfo: "Contact Information",
    shippingInfo: "Delivery Information",
    paymentHeader: "Payment",
    name: "Full Name",
    namePlaceholder: "e.g. Darren",
    phone: "Phone Number",
    phonePlaceholder: "e.g. +60 12-345 6789",
    email: "Email Address",
    emailPlaceholder: "e.g. darren@example.com",
    address: "Delivery Address",
    addressPlaceholder: "e.g. No. 8, Jalan Teluk Sisek, 25000 Kuantan, Pahang",
    deliveryInstruction: "Delivery Instruction",
    deliveryInstructionPlaceholder: "e.g. Leave it in lobby",
    mapBtn: "Pinpoint Current Location",
    locating: "Locating...",
    located: "Location Pinned",
    paymentInstruction: "Please transfer the total amount within 15 minutes to secure your order.",
    accountNameLabel: "Account Name",
    copy: "Copy",
    copied: "Copied!",
    uploadReceipt: "Upload Payment Receipt",
    confirmOrder: "Confirm Order",
    timeRemaining: "Time Remaining",
    orderCancelled: "Order Expired",
    orderCancelledDesc: "You exceeded the 15-minute payment window.",
    orderAgain: "Order Again",
    processing: "Verifying...",
    thankYou: "Order Confirmed!",
    confirmationDesc: "You're on the list! Your pre-order has been successfully received.\nWe look forward to serving you this special menu on your chosen delivery day.\nYour support means the world to us—thank you!",
    chefNote: "Chef's Note",
    nonHalal: "Non-Halal Kitchen",
    cutoff: "Last Order cut-off: 8 PM day before",
    uploadBtn: "Choose File",
    noFile: "No file chosen",
    allergens: "Allergens",
    discoverStory: "Discover Story",
    aiConciergeTitle: "The Wandering Spoon Concierge",
    aiConciergePlaceholder: "Ask about ingredients, spice, or days...",
    storyLoading: "Unfolding the history...",
    chatIntro: "Welcome to The Wandering Spoon! I'm your Nyonya Heritage concierge. Whether you're curious about our aromatic spices, traditional cooking methods, or need a recommendation for your bento journey, I'm delighted to assist you. How may I serve you today?",
    proceedToPayment: "Payment",
    nameError: "Please enter a valid name (min 2 chars)",
    phoneError: "Please enter a valid phone number",
    emailError: "Please enter a valid email address",
    addressError: "Please enter a complete delivery address (min 5 chars)",
    deliveryInstructionError: "Please provide a delivery instruction (min 2 chars).",
    payWithBank: "Bank Transfer",
    payWithTng: "TnG eWallet",
    tngPhoneNumberLabel: "Phone Number",
    orderId: "Order ID",
    estimatedDelivery: "Estimated Delivery Time",
    deliveryWindow: "11:00 AM - 1:00 PM",
    shareOrder: "Share Order Details",
    shareCopied: "Details Copied!",
    shareTitle: "My Order from The Wandering Spoon",
    shareCustomer: "Customer",
    shareItems: "Items",
    shareThanks: "Thank you!",
    editReceipt: "Adjust Receipt",
    rotateLeft: "Rotate Left",
    rotateRight: "Rotate Right",
    confirmChanges: "Confirm & Use Image",
    edit: "Edit",
    previewCrop: "Preview Crop",
    recrop: "Re-crop",
    dragToCrop: "Drag to crop",
    cancelOrder: "Cancel Order?",
    cancelOrderDesc: "Are you sure you want to cancel your order? Your current progress will be lost.",
    confirmCancel: "Yes, Cancel Order",
    keepPaying: "No, Keep Paying",
    timeUpTitle: "Time's Up!",
    timeUpDesc: "Your 15-minute payment window has expired. Would you like to start your order again?",
    backToMenu: "Back to Menu",
    reviewHeader: "Review Order",
    reviewSubheader: "Please check your order details carefully before proceeding to payment.",
    reviewContact: "Contact Details",
    reviewDelivery: "Delivery To",
    reviewItems: "Order Summary",
    reviewConfirm: "Proceed to payment",
    editItems: "Edit Items",
    editDetails: "Edit Details",
    verifyingTitle: "Verifying Payment...",
    verifyingDesc: "Please wait while we check your receipt details, do not refresh the page until confirmation given.",
    verificationFailed: "Verification Failed",
    verificationSuccess: "Payment Verified!",
    retry: "Retry Upload",
    verifyingStep1: "Order details compiled",
    verifyingStep2: "Receipt sent to owner",
    verifyingStep3: "Awaiting manual approval",

    contactHeader: "Contact Information",
    whatsappLabel: "WhatsApp",
    emailLabel: "Email",
    inquiriesLabel: "For any inquiries, you may contact us at",
    orderClosed: "Order Closed",
    notAvailable: "Coming Soon",
    paymentSelectPrompt: "Please select the payment method you actually used to ensure your receipt can be verified correctly.",
    servedWith: "Served With",
    promoDiscount: "10% OFF for 5 or more orders (mix & match).",
    promoDelivery: "Opening Special: Free Delivery to Kuantan Town, IM, Semambu, Sekilau, Air Putih & Alor Akar."
  },
  [Language.ZH]: {
    addToCart: "加入订单",
    soldOut: "售罄",
    limitReached: "达到上限",
    menuHeader: "本周菜单",
    addOnsHeader: "丰富您的用餐体验",
    cartTotal: "总额",
    next: "下一步",
    back: "返回",
    detailsHeader: "配送资料",
    detailsSubheader: "请提供您的联系方式和配送信息，以便我们将美味的餐点送达给您。",
    contactInfo: "联系方式",
    shippingInfo: "配送详情",
    paymentHeader: "付款",
    name: "姓名",
    namePlaceholder: "例：Darren",
    phone: "电话号码",
    phonePlaceholder: "例：+60 12-345 6789",
    email: "电子邮箱",
    emailPlaceholder: "例：darren@example.com",
    address: "配送地址",
    addressPlaceholder: "例：25000 彭亨州关丹 Jalan Teluk Sisek 8号",
    deliveryInstruction: "配送指令",
    deliveryInstructionPlaceholder: "例：请放在大厅",
    mapBtn: "定位当前位置",
    locating: "定位中...",
    located: "已定位",
    paymentInstruction: "请在15分钟内完成转账以保留您的订单。",
    accountNameLabel: "账户名称",
    copy: "复制",
    copied: "已复制!",
    uploadReceipt: "上传付款收据",
    confirmOrder: "确认订单",
    timeRemaining: "剩余时间",
    orderCancelled: "订单已过期",
    orderCancelledDesc: "您已超过15分钟付款时间。",
    orderAgain: "再次订购",
    processing: "验证中...",
    thankYou: "订单已确认!",
    confirmationDesc: "您已在预订名单中！您的预订已成功收到。\n我们期待在您选择的配送日为您奉上这份特别菜单。\n您的支持对我们意义重大——谢谢！",
    chefNote: "主厨寄语",
    nonHalal: "非清真厨房",
    cutoff: "截止时间：前一天晚上8点",
    uploadBtn: "选择文件",
    noFile: "未选择文件",
    allergens: "过敏原",
    discoverStory: "探索故事",
    aiConciergeTitle: "漫游勺 专属客服",
    aiConciergePlaceholder: "询问食材、辣度或日期...",
    storyLoading: "正在展开历史长卷...",
    chatIntro: "欢迎光临漫游勺！我是您的娘惹文化管家。无论您是对我们芬芳的香料、传统的烹饪方式感到好奇，还是需要为您的便当之旅寻求建议，我都非常乐意为您效劳。今天有什么我可以帮您的吗？",
    proceedToPayment: "付款",
    nameError: "请输入有效姓名（至少2个字符）",
    phoneError: "请输入有效电话号码",
    emailError: "请输入有效电子邮箱",
    addressError: "请输入完整配送地址（至少5个字符）",
    deliveryInstructionError: "请输入配送指令（至少2个字符）。",
    payWithBank: "银行转账",
    payWithTng: "TnG 电子钱包",
    tngPhoneNumberLabel: "电话号码",
    orderId: "订单号",
    estimatedDelivery: "预计送达时间",
    deliveryWindow: "上午 11:00 - 下午 1:00",
    shareOrder: "分享订单详情",
    shareCopied: "详情已复制！",
    shareTitle: "我的漫游勺订单",
    shareCustomer: "顾客",
    shareItems: "餐点",
    shareThanks: "谢谢！",
    editReceipt: "调整收据",
    rotateLeft: "向左旋转",
    rotateRight: "向右旋转",
    confirmChanges: "确认并使用图片",
    edit: "编辑",
    previewCrop: "预览裁剪",
    recrop: "重新裁剪",
    dragToCrop: "拖动以裁剪",
    cancelOrder: "取消订单？",
    cancelOrderDesc: "您确定要取消订单吗？当前的订单进度将会丢失。",
    confirmCancel: "是的，取消订单",
    keepPaying: "不，继续支付",
    timeUpTitle: "时间到！",
    timeUpDesc: "您的15分钟支付时间已过。您想重新开始订购吗？",
    backToMenu: "返回菜单",
    reviewHeader: "确认订单",
    reviewSubheader: "在进行付款之前，请仔细检查您的订单详细信息。",
    reviewContact: "联系信息",
    reviewDelivery: "配送至",
    reviewItems: "订单摘要",
    reviewConfirm: "去付款",
    editItems: "编辑餐点",
    editDetails: "编辑资料",
    verifyingTitle: "付款验证中...",
    verifyingDesc: "请稍候，我们正在核对您的收据详情，在确认之前请勿刷新页面。",
    verifyingStep1: "订单详情已汇总",
    verifyingStep2: "收据已发送给店主",
    verifyingStep3: "等待人工审批",
    contactHeader: "联系信息",
    whatsappLabel: "WhatsApp",
    emailLabel: "邮箱",
    inquiriesLabel: "如有任何疑问，请联系我们",
    orderClosed: "订单已关闭",
    notAvailable: "即将开始",
    paymentSelectPrompt: "请选择您实际使用的付款方式，以确保您的收据能够被正确验证。",
    verificationFailed: "验证失败",
    verificationSuccess: "付款已验证！",
    retry: "重试上传",
    servedWith: "搭配",
    promoDiscount: "5份起订享 10% 折扣 (可自由搭配)",
    promoDelivery: "开业特惠：免运费 (Kuantan Town, IM, Semambu, Sekilau, Air Putih, Alor Akar)"
  }
};
